### ISSUE TITLE
Mention v20 upgrades can take a few minutes

### ISSUE THREAD

**Issue by wezrule** [nanocurrency/nano-docs#106]
https://github.com/nanocurrency/nano-node/pull/2283 is modifying all accounts to use the representative account instead of the representative block. This has been found to take a few minutes on some systems.

The `account_info` RPC should mark `rep_block` as deprecated and the representative shown by default when it eventually gets removed, RPC 2.0?

**Comment by zhyatt** [comment]
@wezrule What impacts to node operation are expected during this upgrade time? Is the node still expected to be participating on the network and responding to all RPC calls, etc.?

**Comment by wezrule** [comment]
The upgrade is synchronous and the node won't be participating or queryable during this. Even with the database upgrade for the epoch 2 preparation, the total downtime should be < 10 minutes

**Comment by wezrule** [comment]
Also mention that the ledger may grow in capacity by ~50%. A live ledger went from 16GB (before upgrade) to 24GB after. This is due to essentially copying all the state blocks to a new database while the old ones are still occupying space before being deleted. I experimented with using `mdb_cursor_del` to delete blocks while iterating over the old state v0/v1 databases, but it didn't make a difference to the size. `--vacuum` can be done after which gets it down to about ~13GB

**Comment by guilhermelawless** [comment]
We can note this in the migration page: https://docs.nano.org/releases/node-releases/#v200

**Comment by wezrule** [comment]
And done https://github.com/nanocurrency/nano-docs/pull/156
