### ISSUE TITLE
Expanding the info regarding Nano seed and key derivation

### ISSUE THREAD

**Issue by Joohansson** [nanocurrency/nano-docs#202]
The documentation should be updated at some point regarding the key derivation. I think it's correct info, just missing a few points.
I think it should be written by someone who really knows this, I just found out by trial and error.

For example from here: https://docs.nano.org/integration-guides/the-basics/#seed
PrivK[i] = blake2b(outLen = 32, input = seed || i)

That's true but should be noted that seed is not the same as the BIP39 seed which is 128 in length.

From here: https://docs.nano.org/integration-guides/key-management/
Derived Private Key for 44'/165'/0'

Yes, that's also true but should be noted that type of derivation is not the same as the one mentioned above using blake2b. It results in different private keys!
Should also be mentioned that the 24-word mnemonic can be derived from a Nano 64 length seed using either

[BIP39](https://www.npmjs.com/package/bip39):
mnemonic  = bip39.entropyToMnemonic('seed')

or using nanocurrency-web-js like so:
mnemonic = wallet.generate('seed').mnemonic

Furthermore, the 64 nano seed can also be derived from a 24-word mnemonic by:
seed = bip39.mnemonicToEntropy(mnemonic)

Maybe also mention how to get the private key using both derivation methods (from either [nanocurrency-web-js](https://github.com/numsu/nanocurrency-web-js) or [nanocurrency-js](https://marvinroger.github.io/nanocurrency-js/packages/nanocurrency/)

Default Nano (nanocurrency-js, index 0):
privKey = nano.deriveSecretKey(seed, 0)
Should be the same as blake2b(outLen = 32, input = seed || 0) but haven't tested

Ledger key (nanocurrency-web-js, index 0, seed is 64 char (also called entropy), nanowallet.seed is the 128 char BIP39 seed):
nanowallet = wallet.generate(seed)
accounts = nanowallet.accounts(nanowallet.seed, 0, 0)
privKey = accounts[0].privateKey
This should be the same as BIP39 derivation from 44'/165'/0'

**Comment by zhyatt** [comment]
This is a good callout to improve documentation around seeds/key derivation. @BrianPugh was the original author of some related documentation and mentioned things like derivation path stuff was done sparsely due to it being generic to all crypto. But since those original updates there may be a few things worth expanding on. Any thoughts here @BrianPugh?

**Comment by BrianPugh** [comment]
I think these are all good clarifications that should be added.

**Comment by zhyatt** [comment]
@Joohansson Do the details in https://github.com/nanocurrency/nano-docs/pull/292 properly cover your suggestions?

**Comment by Joohansson** [comment]
@zhyatt It looks great!
