### ISSUE TITLE
Add Node Telemetry details

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-docs#219]
RPC command additions and other details to help make telemetry useful (response definitions?)

Related to: https://github.com/nanocurrency/nano-node/pull/2446 and https://github.com/nanocurrency/nano-node/pull/2521

**Comment by zhyatt** [comment]
Also related: https://github.com/nanocurrency/nano-node/pull/2522 and https://github.com/nanocurrency/nano-node/pull/2524

**Comment by wezrule** [comment]
Also: https://github.com/nanocurrency/nano-node/pull/2560

**Comment by wezrule** [comment]
Done in #231

**Comment by wezrule** [comment]
Also needs: https://github.com/nanocurrency/nano-node/pull/2634 & https://github.com/nanocurrency/nano-node/pull/2618

**Comment by wezrule** [comment]
And https://github.com/nanocurrency/nano-node/pull/2728

**Comment by zhyatt** [comment]
@wezrule Can you verify the published telemetry details across RPC and WebSocket responses? It seems like `active_difficulty`, `address` and `port` are inconsistent between the two.

**Comment by wezrule** [comment]
@zhyatt `active_difficulty` was missing from websocket, good catch! `address` & `port` are always in websocket, but only in RPC when `raw` is set to true. Another possible inconsistency though is that websocket "topic" uses `telemetry` while RPC uses `node_telemetry`, hmm, would it make sense if they were the same?

**Comment by zhyatt** [comment]
@wezrule Thanks for updating. I think consistency would be good here. Perhaps an update on the websocket topic to be `node_telemetry` to be more explicit would make sense.

**Comment by zhyatt** [comment]
Updating all internally to use just `telemetry` while sometimes referred to as "node telemetry" in communications and such. Related https://github.com/nanocurrency/nano-docs/pull/322 and https://github.com/nanocurrency/nano-node/pull/2804
