### ISSUE TITLE
--compare_rep_weights CLI command is unrecognized

### ISSUE THREAD

**Issue by jserv** [nanocurrency/nano-docs#287]
The section [Validating blocks and voting weights](https://docs.nano.org/running-a-node/ledger-management/#validating-blocks-and-voting-weights) mentions ` --compare_rep_weights` CLI command option, which can not be recognized in recent `nano_node`. It should be denoted as V21+ specific command option.

**Comment by zhyatt** [comment]
Thanks @jserv !
