### ISSUE TITLE
Update node crash areas (dump files no longer deleted)

### ISSUE THREAD

**Issue by wezrule** [nanocurrency/nano-docs#437]
Needs updating here:
https://docs.nano.org/running-a-node/troubleshooting/#what-to-do-if-the-node-crashes-linux
&
https://docs.nano.org/commands/command-line-interface/#-debug_generate_crash_report

The dump files are no longer deleted in v22: https://github.com/nanocurrency/nano-node/pull/2915

Also update the v22 section with Docker commands.

**Comment by zhyatt** [comment]
Updated CLI command here https://github.com/nanocurrency/nano-docs/commit/89b04aa6cf76d9b46e91d62a66165396c03df59e - other references to deleting not found.
