### ISSUE TITLE
is it needed to keep RPC-control open for voting

### ISSUE THREAD

**Issue by My1** [nanocurrency/nano-docs#446]
https://docs.nano.org/running-a-node/voting-as-a-representative/

Currently the docs make you open control for setting up the voting (my guess is that it's likely just for creating the wallet and all that) but it is not really clear whether or not control is actually needed for a voting node after the setup (as far as I see it, it shoulndn't tho)

In the interest of security I would propse that if the control is not needed to have it stated that it can be turned off in the docs, if needed I can even help PRing this but first it would make sense to get the facts in.

**Comment by zhyatt** [comment]
Good suggestion. @wezrule Can you confirm that `enable_voting` is not required in the config to allow for voting?

**Comment by My1** [comment]
@zhyatt i think you meant control. Lol

**Comment by wezrule** [comment]
@zhyatt @My1 `enable_control` is only checked when calling some RPCs, it otherwise has no effect, so shouldn't affect voting

**Comment by My1** [comment]
Cool. So that would mean you can safely turn it off after preparing the wallet? That's awesome.

**Comment by wezrule** [comment]
If you don't plan on calling any of the other restricted RPCs then yes should be safe 👍

**Comment by My1** [comment]
Okay made a draft-PR for this, please check.
