### ISSUE TITLE
Grammatical Error on docs.nano.org/protocol-design/ledger/

### ISSUE THREAD

**Issue by derangedhk417** [nanocurrency/nano-docs#467]
Under "Why require two transactions to transfer", the third point says

>  "Allows account owners to ignore transactions, which prevents continuous sending of tiny amounts in an attempt to can prevent use of the account". 

Maybe I'm just sleep deprived (I am), but that seems grammatically incorrect.

**Comment by raitheon** [comment]
Looks like this was fixed in #472  @zhyatt

**Comment by zhyatt** [comment]
Thanks @raitheon and @derangedhk417 - was indeed fixed in #472.
