### ISSUE TITLE
Update the 'edit' button on docs.nano.org that links to GitHub

### ISSUE THREAD

**Issue by raitheon** [nanocurrency/nano-docs#479]
At the top right of each markdown page, there is a link to GitHub in the form of an 'edit' button. For example on the home page the link is: https://github.com/nanocurrency/nano-node/edit/master/docs/index.md, these links 404 as the markdown files are now under a new repo.

**Comment by zhyatt** [comment]
Thanks for noting the issue @raitheon  - should be resolved!
