### ISSUE TITLE
Updates related to removal of elections difficulty sorting

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-docs#526]
https://github.com/nanocurrency/nano-node/pull/3260 - note active_difficulty RPC is deprecated, not removed: https://github.com/nanocurrency/nano-node/pull/3267

**Comment by forresthopkinsa** [comment]
There is no documentation for *why* `active_difficulty` was deprecated or what it should be replaced with. This makes the deprecation message confusing and unhelpful for new users like myself.
