### ISSUE TITLE
Development docker image no longer working

### ISSUE THREAD

**Issue by koczadly** [nanocurrency/nano-docs#592]
Not too familiar with Docker (so I may be doing something wrong), but it seems the suggested `nanocurrency/nano-docs` docker image for testing no longer works.

`docker run ...` gives the following output:
```text
MkDocs encountered as error parsing the configuration file: could not determine a constructor for the tag '!ENV'
  in "/docs/mkdocs.yml", line 175, column 16
```

Even if I change the `!ENV` line to `TRUE`, MkDocs then complains about missing plugins.

**Comment by zhyatt** [comment]
@koczadly I believe this is no longer an issue. Can you confirm?

**Comment by koczadly** [comment]
@zhyatt still getting issues, not sure if I'm just being dumb and missing a step. 

```text
karl@KARL-DESKTOP:/mnt/c/Users/Karl/Documents/Projects/Programming/Nano/nano-docs$ docker run --rm -it -p 8000:8000 -v ${PWD}:/docs nanocurrency/nano-docs:base
INFO    -  Building documentation...

MkDocs encountered as error parsing the configuration file: could not determine a constructor for the tag '!ENV'
  in "/docs/mkdocs.yml", line 186, column 16
```

**Comment by zhyatt** [comment]
@koczadly Ah, I see. We no longer use the Docker hub but instead the github registry. See the setup here: https://github.com/nanocurrency/nano-docs/pkgs/container/nano-docs for more details. Containers are generated and pushed there with each PR and a `latest` tag is available as well. I will look into cleaning up the Docker hub.

**Comment by koczadly** [comment]
Gotcha! You might wanna change the repo readme then - I was following the guidance from there.

**Comment by zhyatt** [comment]
Oh man, thanks @koczadly. The lower part of the Docker instructions were correct but not the main top part. Updated!
