### ISSUE TITLE
Recommend json_block true

### ISSUE THREAD

**Issue by guilhermelawless** [nanocurrency/nano-docs#70]
@zhyatt 
This is available since v19, can we start recommending it now by using it in the documentation examples? The formatted output is much easier to read.

**Comment by guilhermelawless** [comment]
I noticed [this](https://docs.nano.org/integration-guides/key-management/#broadcasting-transactions) example of process does not work for me in linux. `"error": "Unable to parse JSON"`

**Comment by zhyatt** [comment]
Let's move forward with this change
