### ISSUE TITLE
Update config documentation for TOML

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/nano-docs#94]
Add documentation for https://github.com/nanocurrency/nano-node/pull/2221

Do not include a full example anymore, but explain how to generate documented TOML files.

**Comment by guilhermelawless** [comment]
> Do not include a full example anymore

Will we direct the user to the `generate_config` CLI for details on the available configuration?

**Comment by cryptocode** [comment]
I think so, but maybe have additional docs on notable options like we have today.

**Comment by zhyatt** [comment]
Needs --config and --generate_config [node|rpc] to the https://docs.nano.org/commands/command-line-interface/ page

**Comment by guilhermelawless** [comment]
Should we give an example of piping the configuration output to a file?

**Comment by cryptocode** [comment]
Added --config and --generate_config with link to locations for piping. Node operators should know how to pipe output in general imo.

**Comment by argakiig** [comment]
We generate a sample node rpc and pow server toml and bundle for releases. May not be necessary to point out the config generation piping
